;Generated by VELC
section .text
global add
add:
    push rbp
    mov rbp, rsp
    sub rsp, 16
    mov qword [rbp-8], rdi
    mov qword [rbp-16], rsi
    jmp _add_end
_add_end:
    mov rsp, rbp
    pop rbp
    ret

