;Generated by VELC
default rel
section .text

;runtime
global _start
_start:
    endbr64
    ;argc and argv
    mov rdi, qword [rsp]       ;argc
    lea rsi, [rsp+8]           ;argv
    ;envp
    mov rax, rdi
    lea rdx, [rsi + rax*8 + 8] ;rdx = envp
    ;align stack to 16 bytes
    and rsp, -16
    call main
    ;exit
    mov rdi, rax
    mov rax, 0x3c
    syscall




global strlen
strlen:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov qword [rbp-8], rdi ; function parameter str
    push qword 0 ; int literal
    pop rax ; extract initializer expr
    mov qword [rbp-16], rax ; length
_while_1_start:
    push qword [rbp-8] ; str
    pop rax ; cast source value
    push rax ; cast result to Pointer(Builtin(Char))
    pop rax
    movsx rax, byte [rax]
    push rax
    push qword 0 ; int literal
    pop rcx ; binary right
    pop rax ; binary left
    cmp rax, rcx
    setne al
    movzx rax, al
    push rax ; binary result
    
    pop rax ; while condition check
    test rax, rax
    jz _while_1_end
    lea rax, [rbp-16] ; &length
    mov rcx, rax ; postfix address
    mov rax, qword [rcx]
    push rax ; postfix old value
    inc rax
    mov qword [rcx], rax
    pop rax ; discard expr
    lea rax, [rbp-8] ; &str
    push rax ; assignment destination address
    push qword [rbp-8] ; str
    pop rax ; cast source value
    push rax ; cast result to Builtin(Uint64)
    push qword 1 ; int literal
    pop rcx ; binary right
    pop rax ; binary left
    add rax, rcx
    push rax ; binary result
    pop rax ; cast source value
    push rax ; cast result to Builtin(String)
    pop rax ; assignment value
    pop rcx ; assignment destination address
    mov qword [rcx], rax
    push rax ; assignment result
    pop rax ; discard expr
    jmp _while_1_start
_while_1_end:
    push qword [rbp-16] ; length
    pop rax ; put ret value in rax
    jmp _strlen_end ; return
_strlen_end:
    mov rsp, rbp
    pop rbp
    ret





global print_char
print_char:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov byte [rbp-1], dil ; function parameter out
    lea rax, [rbp-1] ; &out
    push rax ; ref result
    pop rax ; extract initializer expr
    mov qword [rbp-9], rax ; outptr
;assembly start
    mov rsi, qword [rbp-9] ; asm input outptr

        mov rax, 1          ; syscall: write
        mov rdi, 1          ; file descriptor: stdout
        ; pointer to message in rsi
        mov rdx, 1          ; message length
        syscall
    
;assembly end
_print_char_end:
    mov rsp, rbp
    pop rbp
    ret





global print_string
print_string:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov qword [rbp-8], rdi ; function parameter str
    push qword [rbp-8] ; str
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call strlen
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; extract initializer expr
    mov qword [rbp-16], rax ; len
;assembly start
    mov rsi, qword [rbp-8] ; asm input str
    mov rdx, qword [rbp-16] ; asm input len

        mov rax, 1          ; syscall: write
        mov rdi, 1          ; file descriptor: stdout
        ; pointer to message in rsi
        ; message length in rdx
        syscall
    
;assembly end
_print_string_end:
    mov rsp, rbp
    pop rbp
    ret





global print_uint
print_uint:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov qword [rbp-8], rdi ; function parameter num
    push qword [rbp-8] ; num
    push qword 10 ; int literal
    pop rcx ; binary right
    pop rax ; binary left
    cmp rax, rcx
    setae al
    movzx rax, al
    push rax ; binary result
    pop rax ; if condition check
    test rax, rax
    jz _if_2_end
    push qword [rbp-8] ; num
    push qword 10 ; int literal
    pop rcx ; binary right
    pop rax ; binary left
    xor rdx, rdx
    div rcx
    push rax ; binary result
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_uint
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
_if_2_end:
    push qword [rbp-8] ; num
    push qword 10 ; int literal
    pop rcx ; binary right
    pop rax ; binary left
    xor rdx, rdx
    div rcx
    mov rax, rdx
    push rax ; binary result
    push qword 48 ; char literal
    pop rcx ; binary right
    pop rax ; binary left
    add rax, rcx
    push rax ; binary result
    pop rax ; cast source value
    movsx rax, al
    push rax ; cast result to Builtin(Char)
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_char
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
_print_uint_end:
    mov rsp, rbp
    pop rbp
    ret





global print_int
print_int:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov qword [rbp-8], rdi ; function parameter num
    push qword [rbp-8] ; num
    push qword 0 ; int literal
    pop rcx ; binary right
    pop rax ; binary left
    cmp rax, rcx
    setl al
    movzx rax, al
    push rax ; binary result
    pop rax ; if condition check
    test rax, rax
    jz _if_3_else
    push qword 45 ; char literal
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_char
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    push qword 0 ; int literal
    push qword [rbp-8] ; num
    pop rcx ; binary right
    pop rax ; binary left
    sub rax, rcx
    push rax ; binary result
    pop rax ; cast source value
    push rax ; cast result to Builtin(Uint64)
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_uint
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    jmp _if_3_end
_if_3_else:
    push qword [rbp-8] ; num
    pop rax ; cast source value
    push rax ; cast result to Builtin(Uint64)
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_uint
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
_if_3_end:
_print_int_end:
    mov rsp, rbp
    pop rbp
    ret





global print_bool
print_bool:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov byte [rbp-1], dil ; function parameter value
    movzx rax, byte [rbp-1] ; value
    push rax ; value
    pop rax ; if condition check
    test rax, rax
    jz _if_4_end
    push _str_5
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_string
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    jmp _print_bool_end ; return
_if_4_end:
    push _str_6
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_string
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
_print_bool_end:
    mov rsp, rbp
    pop rbp
    ret





global println
println:
    endbr64
    push rbp
    mov rbp, rsp
    sub rsp, 16 ; function locals
    mov qword [rbp-8], rdi ; function parameter str
    push qword [rbp-8] ; str
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_string
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    push qword 10 ; char literal
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_char
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
_println_end:
    mov rsp, rbp
    pop rbp
    ret





global main
main:
    endbr64
    push rbp
    mov rbp, rsp
    push _str_7
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_string
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    push qword 1 ; bool literal
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call print_bool
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    push _str_8
    pop rdi ; call argument 0
    mov r10, rsp ; save caller rsp before call
    and rsp, -16
    sub rsp, 16
    mov [rsp], r10
    call println
    mov rsp, [rsp] ; restore caller rsp after call
    push rax ; call result
    pop rax ; discard expr
    push qword 0 ; int literal
    pop rax ; put ret value in rax
    jmp _main_end ; return
_main_end:
    mov rsp, rbp
    pop rbp
    ret






section .rodata
    _str_5 db "true", 0
    _str_6 db "false", 0
    _str_7 db "I love vel: ", 0
    _str_8 db 0

