use crate::compiler::parser::*;
use std::collections::{HashMap, BTreeMap};

#[derive(Debug, Clone)]
pub struct FunctionFrame {
    pub stack_size: usize,
    pub locals: HashMap<String, isize>, // rbp-relative offsets, usually negative
}



#[derive(Default, Debug, Clone)]
pub struct CodeGenerator {
    debug: bool,
    sections: BTreeMap<String, String>,

    label_id: usize,
    current_function: Option<String>,
    current_frame: Option<FunctionFrame>,
    loop_stack: Vec<(String, String)>, // (continue_label, break_label)
}
impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            debug: false,

            sections: BTreeMap::new(),

            label_id: 0,
            current_function: None,
            current_frame: None,
            loop_stack: Vec::new(),
        }
    }
    pub fn run(&mut self, program: &Program, debug: bool) -> Result<String, String> {
        self.debug = debug;
        
        self.emit_program(program)?;
    
        let mut out = String::from(";Generated by VELC\n");

        let ordered_sections = ["text", "data", "bss", "rodata"];

        for section in ordered_sections {
            if let Some(contents) = self.sections.get(section) {
                out.push_str(&format!("section .{}\n", section));
                out.push_str(contents);
                if !contents.ends_with('\n') {
                    out.push('\n');
                }
                out.push('\n');
            }
        }

        for (section, contents) in &self.sections {
            if ordered_sections.contains(&section.as_str()) {
                continue;
            }

            out.push_str(&format!("section .{}\n", section));
            out.push_str(contents);
            if !contents.ends_with('\n') {
                out.push('\n');
            }
            out.push('\n');
        }

        Ok(out)
    }

    fn next_label_id(&mut self) -> usize {
        self.label_id += 1;
        self.label_id
    }    
    fn generate_label(&mut self, prefix: &str) -> String {
        format!("{}_{}", prefix, self.next_label_id())
    }

    fn push_section(&mut self, section: &str, text: &str) -> Result<(), String> {
        let section_name = match section {
            "" => "text",
            other => other,
        };

        let buf = self.sections.entry(section_name.to_string()).or_default();
        buf.push_str(text);
        if !text.ends_with('\n') {
            buf.push('\n');
        }

        Ok(())
    }
    fn debug_str(&mut self, text: &str, pad: &str) -> String {
        format!(";{pad} start\n{text};{pad} end\n")
    }

    fn emit_program(&mut self, program: &Program) -> Result<(), String> {
        for item in &program.items {
            self.emit_top_level(item)?;
        }
        Ok(())
    }
    fn emit_top_level(&mut self, item: &TopLevel) -> Result<(), String> {

        match item {
            TopLevel::Function(decl) => {
                self.emit_function(decl)?;
            }
            TopLevel::GlobalVar(decl) => {
                self.emit_global_var(decl)?;
            }
            TopLevel::Assembly(decl) => {
                self.emit_top_level_asm(decl)?;
            }
        };

        Ok(())
    }
    fn emit_top_level_asm(&mut self, decl: &AssemblyDecl) -> Result<(), String> {

        let mut text = String::new();

        //inputs: move global values into regs
        let mut inputs_text = String::new();
        for i in &decl.inputs {
            inputs_text.push_str(&format!("mov {}, [{}]\n", i.reg, i.name));
        }
        if !inputs_text.is_empty() && self.debug {inputs_text = format!(";asm inputs: \n{inputs_text};-------");}

        //outputs: move regs into global values
        let mut outputs_text = String::new();
        for i in &decl.outputs {
            outputs_text.push_str(&format!("mov [{}], {}\n", i.name, i.reg));
        }
        if !outputs_text.is_empty() && self.debug {outputs_text = format!(";asm outputs: \n{outputs_text};-------");}

        text.push_str(&inputs_text);
        text.push_str(&decl.code);
        text.push_str(&outputs_text);

        self.push_section(&decl.section, &text)?;

        Ok(())
    }
    fn emit_global_var(&mut self, decl: &VarDecl) -> Result<(), String> {
        Ok(())
    }
    fn emit_function(&mut self, decl: &FunctionDecl) -> Result<(), String> {
        Ok(())
    }

    fn error<T>(&mut self, base: &str, err: &str) -> Result<T, String> {
        Err(format!("{base}:{err}\n"))
    }

}

