use crate::compiler::parser::*;
use std::collections::{BTreeMap, HashMap};

#[derive(Default, Debug, Clone)]
pub struct FunctionFrame {
    pub name: String,
    pub stack_size: usize,
    pub current_local_offset: isize,
    pub local_scopes: Vec<HashMap<String, (isize, TypeName)>>, //identifier, (offset from rbp, type)
}

#[derive(Debug, Clone)]
pub enum Sign {
    Unsigned,
    Signed,
}

#[derive(Default, Debug, Clone)]
pub struct CodeGenerator {
    debug: bool,
    sections: BTreeMap<String, String>,

    label_id: usize,

    globals: HashMap<String, TypeName>, //identifier, type
    func: FunctionFrame,
    loop_stack: Vec<(String, String)>, // (continue_label, break_label)
}
impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            debug: false,
            sections: BTreeMap::new(),

            label_id: 0,

            globals: HashMap::new(),
            func: FunctionFrame::default(),
            loop_stack: Vec::new(),
        }
    }
    pub fn run(&mut self, program: &Program, debug: bool) -> Result<String, String> {
        self.debug = debug;
        
        self.emit_start()?;
        self.emit_program(program)?;
    
        let mut out = String::from(";Generated by VELC\n");
        out.push_str("default rel\n");

        let ordered_sections = ["text", "data", "bss", "rodata"];

        for section in ordered_sections {
            if let Some(contents) = self.sections.get(section) {
                out.push_str(&format!("section .{}\n", section));
                out.push_str(contents);
                if !contents.ends_with('\n') {
                    out.push('\n');
                }
                out.push('\n');
            }
        }

        for (section, contents) in &self.sections {
            if ordered_sections.contains(&section.as_str()) {
                continue;
            }

            out.push_str(&format!("section .{}\n", section));
            out.push_str(contents);
            if !contents.ends_with('\n') {
                out.push('\n');
            }
            out.push('\n');
        }

        Ok(out)
    }

    fn next_label_id(&mut self) -> usize {
        self.label_id += 1;
        self.label_id
    }    

    fn push_section(&mut self, section: &str, text: &str) -> Result<(), String> {
        let section_name = match section {
            "" => "text",
            other => other,
        };

        let buf = self.sections.entry(section_name.to_string()).or_default();
        buf.push_str(text);
        if !text.ends_with('\n') {
            buf.push('\n');
        }

        Ok(())
    }
    fn debug_str(&mut self, text: &str, pad: &str) -> String {
        format!(";{pad} start\n{text};{pad} end\n")
    }

    fn type_size(&self, Type: &TypeName) -> Result<usize, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:type_size";
    
        match Type {
            TypeName::Builtin(BuiltinType::Bool) => Ok(1),
            TypeName::Builtin(BuiltinType::Int8) => Ok(1),
            TypeName::Builtin(BuiltinType::Uint8) => Ok(1),
            TypeName::Builtin(BuiltinType::Char) => Ok(1),
    
            TypeName::Builtin(BuiltinType::Int16) => Ok(2),
            TypeName::Builtin(BuiltinType::Uint16) => Ok(2),
    
            TypeName::Builtin(BuiltinType::Int32) => Ok(4),
            TypeName::Builtin(BuiltinType::Uint32) => Ok(4),
            TypeName::Builtin(BuiltinType::Float32) => Ok(4),
    
            TypeName::Builtin(BuiltinType::Int64) => Ok(8),
            TypeName::Builtin(BuiltinType::Uint64) => Ok(8),
            TypeName::Builtin(BuiltinType::Float64) => Ok(8),
    
            TypeName::Builtin(BuiltinType::String) => Ok(8), // pointer
            TypeName::Pointer(_) => Ok(8),
    
            _ => self.error(ERROR_STRING_ROOT, &format!("Unsupported global type size for {:?}", Type)),
        }
    }
    fn type_sign(&self, Type: &TypeName) -> Result<Sign, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:type_sign";
    
        let ret = match Type {
            TypeName::Builtin(BuiltinType::Bool) => Sign::Unsigned,
            TypeName::Builtin(BuiltinType::Int8) => Sign::Signed,
            TypeName::Builtin(BuiltinType::Uint8) => Sign::Unsigned,
            TypeName::Builtin(BuiltinType::Char) => Sign::Signed,
    
            TypeName::Builtin(BuiltinType::Int16) => Sign::Signed,
            TypeName::Builtin(BuiltinType::Uint16) => Sign::Unsigned,
    
            TypeName::Builtin(BuiltinType::Int32) => Sign::Signed,
            TypeName::Builtin(BuiltinType::Uint32) => Sign::Unsigned,
            TypeName::Builtin(BuiltinType::Float32) => Sign::Signed,
    
            TypeName::Builtin(BuiltinType::Int64) => Sign::Signed,
            TypeName::Builtin(BuiltinType::Uint64) => Sign::Unsigned,
            TypeName::Builtin(BuiltinType::Float64) => Sign::Signed,
    
            TypeName::Builtin(BuiltinType::String) => Sign::Unsigned, // pointer
            TypeName::Pointer(_) => Sign::Unsigned,
    
            _ => return self.error(ERROR_STRING_ROOT, &format!("Unsupported global type size for {:?}", Type)),
        };
        Ok(ret)
    }
    fn size_specifier(&self, size: usize) -> Result<String, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:size_specifier";
    
        let ret = match size {
            1 => "byte",
            2 => "word",
            4 => "dword",
            8 => "qword",
            n => {return self.error(ERROR_STRING_ROOT, &format!("Unsupported bss size {}", n));}
        }.to_string();

        Ok(ret)
    }
    fn data_directive(&self, Type: &TypeName) -> Result<&'static str, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:data_directive";
    
        match self.type_size(Type)? {
            1 => Ok("db"),
            2 => Ok("dw"),
            4 => Ok("dd"),
            8 => Ok("dq"),
            n => self.error(ERROR_STRING_ROOT, &format!("Unsupported data size {}", n)),
        }
    }
    fn bss_directive(&self, Type: &TypeName) -> Result<&'static str, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:bss_directive";
    
        match self.type_size(Type)? {
            1 => Ok("resb"),
            2 => Ok("resw"),
            4 => Ok("resd"),
            8 => Ok("resq"),
            n => self.error(ERROR_STRING_ROOT, &format!("Unsupported bss size {}", n)),
        }
    }

    fn format_nasm_string_bytes(&self, s: &str) -> String {
        let mut parts: Vec<String> = Vec::new();
        let mut current = String::new();

        for ch in s.chars() {
            match ch {
                '\n' => {
                    if !current.is_empty() {
                        parts.push(format!("\"{}\"", current));
                        current.clear();
                    }
                    parts.push("10".to_string());
                }
                '\r' => {
                    if !current.is_empty() {
                        parts.push(format!("\"{}\"", current));
                        current.clear();
                    }
                    parts.push("13".to_string());
                }
                '\t' => {
                    if !current.is_empty() {
                        parts.push(format!("\"{}\"", current));
                        current.clear();
                    }
                    parts.push("9".to_string());
                }
                '\0' => {
                    if !current.is_empty() {
                        parts.push(format!("\"{}\"", current));
                        current.clear();
                    }
                    parts.push("0".to_string());
                }
                '"' => {
                    current.push('"');
                    current.push('"'); // NASM escapes " inside strings by doubling it
                }
                _ => {
                    current.push(ch);
                }
            }
        }

        if !current.is_empty() {
            parts.push(format!("\"{}\"", current));
        }

        parts.push("0".to_string()); // null terminator
        parts.join(", ")
    }
    fn emit_static_initializer_value(&mut self, expr: &Expr) -> Result<String, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_static_initializer_value";
    
        match expr {
            Expr::BoolLiteral(v) => {
                Ok(if *v { "1".to_string() } else { "0".to_string() })
            }
    
            Expr::IntLiteral(v) => {
                Ok(v.to_string())
            }
    
            Expr::FloatLiteral(v) => {
                Ok(v.to_string())
            }
    
            Expr::CharLiteral(c) => {
                Ok((*c as u32).to_string())
            }
    
            Expr::StringLiteral(s) => {
                let label = format!("_str_{}", self.next_label_id());
                let bytes = self.format_nasm_string_bytes(s);
                self.push_section("rodata", &format!("    {} db {}", label, bytes))?;
                Ok(label)
            }
    
            Expr::Cast { expr, .. } => {
                self.emit_static_initializer_value(expr)
            }
    
            Expr::Identifier(name) => {
                Ok(name.clone())
            }
    
            _ => {
                self.error(
                    ERROR_STRING_ROOT,
                    &format!("Unsupported static global initializer {:?}", expr),
                )
            }
        }
    }

    fn build_function_frame(&mut self, decl: &FunctionDecl) -> Result<FunctionFrame, String> {

        let mut locals_size = 0; //size locals take up in bytes
        let mut locals_count = 0; //number of locals

        for s in &decl.params {
            locals_size += self.type_size(&s.Type)?;
            locals_count += 1;
        }

        self.collect_function_locals(&decl.body, &mut locals_size, &mut locals_count)?;

        let stack_size = ((locals_size + 15) / 16) * 16; //16 byte alignment

        if self.debug {println!("Function {} has {} locals, {}B stack(real {}B)", decl.name, locals_count, stack_size, locals_size)}

        Ok(FunctionFrame{
            name: decl.name.clone(),
            stack_size: stack_size,
            current_local_offset: 0,
            local_scopes: Vec::new(),
        })
    }
    fn collect_function_locals(&mut self, stmt: &Stmt, size: &mut usize, count: &mut u32) -> Result<(), String> {
        match stmt {
            Stmt::Block(stmts) => {
                for stmt in stmts {
                    self.collect_function_locals(stmt, size, count)?;
                }
            }
    
            Stmt::VarDecl(decl) => {
                *size += self.type_size(&decl.Type)?;
                *count += 1;
            }
    
            Stmt::If { then_branch, else_branch, .. } => {
                self.collect_function_locals(then_branch, size, count)?;
                if let Some(else_branch) = else_branch {
                    self.collect_function_locals(else_branch, size, count)?;
                }
            }
    
            Stmt::While { body, .. } => {
                self.collect_function_locals(body, size, count)?;
            }
    
            Stmt::For { init, body, .. } => {
                if let Some(ForInit::VarDecl(decl)) = init {
                    *size += self.type_size(&decl.Type)?;
                    *count += 1;
                }
                self.collect_function_locals(body, size, count)?;
            }
            _ => {}
        }
    
        Ok(())
    }
    fn lookup_global_var(&self, name: &str) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:lookup_global_var";

        if let Some(typen) = self.globals.get(name) {
            return Ok((*typen).clone());
        }

        self.error(ERROR_STRING_ROOT, &format!("Unknown global '{}'", name))
    }
    fn lookup_local_var(&self, name: &str) -> Result<(isize, TypeName), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:lookup_local_var";

        for scope in self.func.local_scopes.iter().rev() {
            if let Some(dd) = scope.get(name) {
                return Ok((*dd).clone());
            }
        }

        self.error(ERROR_STRING_ROOT, &format!("Unknown local '{}'", name))
    }
    fn format_offset(&self, offset: isize) -> String {
        if offset < 0 {
            format!("-{}", -offset)
        }
        else {
            format!("+{}", offset)
        }
    }
    fn format_reg_size(&self, reg: &str, size: usize) -> Result<String, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:format_reg_size";

        let new_reg = match (reg, size) {
            // rax family
            ("rax", 8) => "rax",
            ("rax", 4) => "eax",
            ("rax", 2) => "ax",
            ("rax", 1) => "al",
    
            // rbx family
            ("rbx", 8) => "rbx",
            ("rbx", 4) => "ebx",
            ("rbx", 2) => "bx",
            ("rbx", 1) => "bl",
    
            // rcx family
            ("rcx", 8) => "rcx",
            ("rcx", 4) => "ecx",
            ("rcx", 2) => "cx",
            ("rcx", 1) => "cl",
    
            // rdx family
            ("rdx", 8) => "rdx",
            ("rdx", 4) => "edx",
            ("rdx", 2) => "dx",
            ("rdx", 1) => "dl",
    
            // rsi family
            ("rsi", 8) => "rsi",
            ("rsi", 4) => "esi",
            ("rsi", 2) => "si",
            ("rsi", 1) => "sil",
    
            // rdi family
            ("rdi", 8) => "rdi",
            ("rdi", 4) => "edi",
            ("rdi", 2) => "di",
            ("rdi", 1) => "dil",
    
            // rbp family
            ("rbp", 8) => "rbp",
            ("rbp", 4) => "ebp",
            ("rbp", 2) => "bp",
            ("rbp", 1) => "bpl",
    
            // rsp family
            ("rsp", 8) => "rsp",
            ("rsp", 4) => "esp",
            ("rsp", 2) => "sp",
            ("rsp", 1) => "spl",
    
            // r8-r15 families
            ("r8", 8) => "r8",
            ("r8", 4) => "r8d",
            ("r8", 2) => "r8w",
            ("r8", 1) => "r8b",
    
            ("r9", 8) => "r9",
            ("r9", 4) => "r9d",
            ("r9", 2) => "r9w",
            ("r9", 1) => "r9b",
    
            ("r10", 8) => "r10",
            ("r10", 4) => "r10d",
            ("r10", 2) => "r10w",
            ("r10", 1) => "r10b",
    
            ("r11", 8) => "r11",
            ("r11", 4) => "r11d",
            ("r11", 2) => "r11w",
            ("r11", 1) => "r11b",
    
            ("r12", 8) => "r12",
            ("r12", 4) => "r12d",
            ("r12", 2) => "r12w",
            ("r12", 1) => "r12b",
    
            ("r13", 8) => "r13",
            ("r13", 4) => "r13d",
            ("r13", 2) => "r13w",
            ("r13", 1) => "r13b",
    
            ("r14", 8) => "r14",
            ("r14", 4) => "r14d",
            ("r14", 2) => "r14w",
            ("r14", 1) => "r14b",
    
            ("r15", 8) => "r15",
            ("r15", 4) => "r15d",
            ("r15", 2) => "r15w",
            ("r15", 1) => "r15b",
    
            // Invalid register or invalid size
            _ => {
                return self.error(ERROR_STRING_ROOT, &format!(
                    "Cannot format register name `{}` to `{}` bytes",
                    reg, size
                ));
            }
        }.to_string();
        Ok(new_reg)
    }
    fn arg_register(&self, index: usize) -> Option<String> {
        let ret = match index {
            0 => "rdi",
            1 => "rsi",
            2 => "rdx",
            3 => "rcx",
            4 => "r8",
            5 => "r9",
            _ => {return None;},
        };
        Some(ret.to_string())
    }
    fn get_next_local_slot(&mut self, Type: &TypeName) -> Result<(isize, TypeName), String> {
        let type_size = self.type_size(Type)?;
        self.func.current_local_offset -= type_size as isize;
        Ok((self.func.current_local_offset, Type.clone()))
    }

    fn emit_program(&mut self, program: &Program) -> Result<(), String> {
        for item in &program.items {
            self.emit_top_level(item)?;
        }
        Ok(())
    }
    fn emit_top_level(&mut self, item: &TopLevel) -> Result<(), String> {
        match item {
            TopLevel::Function(decl) => {
                self.emit_function(decl)?;
            }
            TopLevel::GlobalVar(decl) => {
                self.emit_global_var(decl)?;
            }
            TopLevel::Assembly(decl) => {
                self.emit_top_level_asm(decl)?;
            }
        };

        Ok(())
    }
    fn emit_top_level_asm(&mut self, decl: &AssemblyDecl) -> Result<(), String> {
        let mut text = String::new();

        //inputs: move global values into regs
        let mut inputs_text = String::new();
        for i in &decl.inputs {
            let t: TypeName = self.lookup_global_var(&i.name)?;
            let typesize = self.type_size(&t)?;
            inputs_text.push_str(&format!("mov {}, {} [{}]\n", 
                self.format_reg_size(&i.reg, typesize)?, 
                self.size_specifier(typesize)?,
                i.name));
        }
        if !inputs_text.is_empty() && self.debug {inputs_text = format!(";asm inputs: \n{inputs_text};-------\n");}

        //outputs: move regs into global values
        let mut outputs_text = String::new();
        for i in &decl.outputs {
            let t: TypeName = self.lookup_global_var(&i.name)?;
            let typesize = self.type_size(&t)?;
            outputs_text.push_str(&format!("mov {} [{}], {}\n", 
                self.size_specifier(typesize)?,
                i.name, 
                self.format_reg_size(&i.reg, typesize)?));
        }
        if !outputs_text.is_empty() && self.debug {outputs_text = format!("\n;asm outputs: \n{outputs_text}\n;-------");}

        text.push_str(&inputs_text);
        text.push_str(&decl.code);
        text.push_str(&outputs_text);

        if self.debug {self.push_section(&decl.section, ";global assembly start")?;}

        self.push_section(&decl.section, &text)?;

        if self.debug {self.push_section(&decl.section, ";global assembly end")?;}

        Ok(())
    }
    fn emit_global_var(&mut self, decl: &VarDecl) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_global_var";
        self.globals.insert(
            decl.name.clone(),
            decl.Type.clone()
        );
        match &decl.init {
            Some(init) => {
                let dir = self.data_directive(&decl.Type)?;
                let value = self.emit_static_initializer_value(init)?;
    
                self.push_section(
                    "data",
                    &format!("    {} {} {}", decl.name, dir, value),
                )?;
    
                Ok(())
            }
            None => {
                let dir = self.bss_directive(&decl.Type)?;
    
                self.push_section(
                    "bss",
                    &format!("    {} {} 1", decl.name, dir),
                )?;
    
                Ok(())
            }
        }
    }
    fn emit_function(&mut self, decl: &FunctionDecl) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_function";

        //clear state
        self.loop_stack.clear();

        //calculates size of function locals
        self.func = self.build_function_frame(decl)?;

        //Function label
        self.push_section("text", &format!("global {}", decl.name))?;
        self.push_section("text", &format!("{}:", decl.name))?;

        //Function start stack frame
        self.push_section("text", "    endbr64")?;
        self.push_section("text", "    push rbp")?;
        self.push_section("text", "    mov rbp, rsp")?;

        //reserve space for locals
        if self.func.stack_size > 0 {
            self.push_section("text", &format!("    sub rsp, {}\n", self.func.stack_size))?;
        }

        //put register parameters into stack slots
        let mut parameter_scope = HashMap::new();

        for (i, param) in decl.params.iter().enumerate() {
            let reg = match self.arg_register(i) {
                Some(reg) => reg,
                None => {
                    return self.error(
                        ERROR_STRING_ROOT,
                        "More than 6 parameters not yet supported",
                    );
                }
            };
            let (offset, t) = self.get_next_local_slot(&param.Type)?;
            let size = self.type_size(&t)?;
            parameter_scope.insert(param.name.clone(), (offset, t));

            self.push_section("text", &format!("    mov {} [rbp{}], {} ; {}",
                self.size_specifier(size)?,
                self.format_offset(offset),
                self.format_reg_size(&reg, size)?,
                param.name
            ))?;
        }
        self.func.local_scopes.push(parameter_scope);

        let end_label = format!("_{}_end", decl.name);
        
        //function body
        self.emit_stmt(&decl.body, &end_label)?;

        //return label
        self.push_section("text", &format!("{}:", end_label))?;

        //end stack frame
        self.push_section("text", "    mov rsp, rbp")?;
        self.push_section("text", "    pop rbp")?;
        self.push_section("text", "    ret")?;

        //clear state
        self.func = FunctionFrame::default();
        self.loop_stack.clear();

        Ok(())
    }
    fn emit_start(&mut self) -> Result<(), String> {
        self.push_section("text", "
;runtime code
global _start
_start:
    endbr64
    ;argc and argv
    mov rdi, qword [rsp]       ;argc
    lea rsi, [rsp+8]           ;argv
    ;envp
    mov rax, rdi
    lea rdx, [rsi + rax*8 + 8] ;rdx = envp
    ;align stack to 16 bytes
    and rsp, -16
    call main
    ;exit
    mov rdi, rax
    mov rax, 60
    syscall




")
    }
    fn emit_assembly(&mut self, decl: &AssemblyDecl) -> Result<String, String> {
        let mut text = String::new();

        //inputs: move local values into regs
        let mut inputs_text = String::new();
        for i in &decl.inputs {
            if let Ok(te) = self.lookup_local_var(&i.name) {
                let (offset, t) = te;
                let typesize = self.type_size(&t)?;
                inputs_text.push_str(&format!("    mov {}, {} [rbp{}] ; {}\n",
                    self.format_reg_size(&i.reg, typesize)?,
                    self.size_specifier(typesize)?,
                    self.format_offset(offset),
                    i.name
                ));
            }
            else {
                let t: TypeName = self.lookup_global_var(&i.name)?;
                let typesize = self.type_size(&t)?;
                inputs_text.push_str(&format!("    mov {}, {} [{}] ; {}\n", 
                    self.format_reg_size(&i.reg, typesize)?, 
                    self.size_specifier(typesize)?,
                    i.name,
                    i.name
                ));
            }
        }
        if !inputs_text.is_empty() && self.debug {inputs_text = format!(";asm inputs: \n{inputs_text};-------\n");}

        //outputs: move regs into global values
        let mut outputs_text = String::new();
        for i in &decl.outputs {
            if let Ok(te) = self.lookup_local_var(&i.name) {
                let (offset, t) = te;
                let typesize = self.type_size(&t)?;
                outputs_text.push_str(&format!("    mov {} [rbp{}], {} ; {}\n",
                    self.size_specifier(typesize)?,
                    self.format_offset(offset),
                    self.format_reg_size(&i.reg, typesize)?,
                    i.name
                ));
            }
            else {
                let t: TypeName = self.lookup_global_var(&i.name)?;
                let typesize = self.type_size(&t)?;
                outputs_text.push_str(&format!("    mov {} [{}], {} ; {}\n", 
                    self.size_specifier(typesize)?,
                    i.name,
                    self.format_reg_size(&i.reg, typesize)?,
                    i.name
                ));
            }
        }
        if !outputs_text.is_empty() && self.debug {outputs_text = format!("\n;asm outputs: \n{outputs_text}\n;-------");}

        text.push_str(&inputs_text);
        text.push_str(&decl.code);
        text.push_str(&outputs_text);

        if self.debug {self.push_section(&decl.section, ";assembly start")?;}

        self.push_section(&decl.section, &text)?;

        if self.debug {self.push_section(&decl.section, ";assembly end")?;}

        Ok(text)
    }
    fn emit_stmt(&mut self, stmt: &Stmt, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_stmt";

        match stmt {
            Stmt::Block(stmts) => {
                self.emit_block(stmts, ret_label)?;
            }
            Stmt::VarDecl(decl) => {
                self.emit_var(decl, ret_label)?;
            }
            Stmt::Return(ret) => {
                self.emit_return(ret, ret_label)?;
            }
            Stmt::Break => {
                self.emit_break(ret_label)?;
            }
            Stmt::Continue => {
                self.emit_continue(ret_label)?;
            }
            Stmt::While{cond, body} => {
                self.emit_while(cond, body, ret_label)?;
            }
            Stmt::If{cond, then_branch, else_branch} => {
                self.emit_if(cond, then_branch, else_branch, ret_label)?;
            }
            Stmt::For{init, cond, step, body} => {
                self.emit_for(init, cond, step, body, ret_label)?;
            }
            Stmt::Expr(expr) => {
                self.emit_expr_stmt(expr, ret_label)?;
            }
            Stmt::Assembly(asm) => {
                self.emit_assembly(asm)?;
            }
            Stmt::Empty => {
                self.push_section("text", "nop ; do nothing :3")?;
            }
        }

        Ok(())
    }
    fn emit_block(&mut self, stmts: &Vec<Stmt>, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_block";
        self.func.local_scopes.push(HashMap::new());
        for s in stmts {
            self.emit_stmt(s, ret_label)?;
        }
        self.func.local_scopes.pop();
        Ok(())
    }
    fn emit_expr_stmt(&mut self, expr: &Expr, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_expr_stmt";
        self.emit_expr(expr)?;
        self.push_section("text", "    pop rax")?;
        Ok(())
    }
    fn emit_var(&mut self, decl: &VarDecl, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_expr_stmt";
        let (offset, t) = self.get_next_local_slot(&decl.Type)?;
        let size = self.type_size(&t)?;

        let map = self.func.local_scopes.last_mut().unwrap();
        map.insert(decl.name.clone(), (offset, t));

        let mut text = String::new();
        if let Some(init) = decl.init.clone() {
            self.emit_expr(&init)?;

            text.push_str("    pop rax\n");

            text.push_str(&format!(
                "    mov {} [rbp{}], {}",
                self.size_specifier(size)?,
                self.format_offset(offset),
                self.format_reg_size("rax", size)?
            ));
        }

        self.push_section("text", &text)?;
        Ok(())
    }
    fn emit_return(&mut self, ret: &Option<Expr>, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_return";
        let mut text = String::new();
        if let Some(expr) = ret {
            self.emit_expr(expr)?;
            text.push_str("    pop rax\n");
        }
        text.push_str(&format!(
            "    jmp {ret_label}"
        ));

        self.push_section("text", &text)?;
        Ok(())
    }
    fn emit_break(&mut self, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_break";
        let label = self.loop_stack.last().unwrap();
                
        let text = format!(
            "    jmp {}", 
            label.1
        );

        self.push_section("text", &text)?;
        Ok(())
    }
    fn emit_continue(&mut self, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_continue";
        let label = self.loop_stack.last().unwrap();
                
        let text = format!(
            "    jmp {}", 
            label.0
        );

        self.push_section("text", &text)?;
        Ok(())
    }
    fn emit_while(&mut self, cond: &Expr, body: &Box<Stmt>, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_while";
        let label_id = self.next_label_id();
        let start_label = format!("_while_{}_start", label_id);
        let end_label = format!("_while_{}_end", label_id);

        self.loop_stack.push((start_label.clone(), end_label.clone()));

        self.push_section("text", &format!("{start_label}:"))?;
        self.emit_expr(cond)?;
        self.push_section("text", &format!("    
    pop rax
    test rax, rax
    jz {end_label}
"))?;
        self.emit_stmt(body, ret_label)?;
        self.push_section("text", &format!("    jmp {start_label}"))?;
        self.push_section("text", &format!("{end_label}:"))?;

        self.loop_stack.pop();
        Ok(())
    }
    fn emit_if(&mut self, cond: &Expr, then_branch: &Stmt, else_branch: &Option<Box<Stmt>>, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_if";
        let label_id = self.next_label_id();
        let else_label = format!("_if_{}_else", label_id);
        let end_label = format!("_if_{}_end", label_id);
        self.emit_expr(cond)?;
        self.push_section("text", "    pop rax")?;
        self.push_section("text", "    test rax, rax")?;
        if else_branch.is_some() {
            self.push_section("text", &format!("    jz {}", else_label))?;
            self.emit_stmt(then_branch, ret_label)?;
            self.push_section("text", &format!("    jmp {}", end_label))?;
            self.push_section("text", &format!("{}:", else_label))?;
            self.emit_stmt(else_branch.as_ref().unwrap(), ret_label)?;
            self.push_section("text", &format!("{}:", end_label))?;
        }
        else {
            self.push_section("text", &format!("    jz {}", end_label))?;
            self.emit_stmt(then_branch, ret_label)?;
            self.push_section("text", &format!("{}:", end_label))?;
        }
        Ok(())
    }
    fn emit_for(&mut self, init: &Option<ForInit>, cond: &Option<Expr>, step: &Option<Expr>, body: &Stmt, ret_label: &str) -> Result<(), String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_for";
        let label_id = self.next_label_id();
        let start_label = format!("_for_{}_start", label_id);
        let step_label = format!("_for_{}_step", label_id);
        let end_label = format!("_for_{}_end", label_id);

        self.func.local_scopes.push(HashMap::new()); //scope for init

        //init
        if let Some(init) = init {
            match init {
                ForInit::VarDecl(decl) => {
                    self.emit_stmt(&Stmt::VarDecl(decl.clone()), ret_label)?;
                }
                ForInit::Expr(expr) => {
                    self.emit_expr(expr)?;
                    self.push_section("text", "    pop rax")?;
                }
            }
        }

        //condition
        self.push_section("text", &format!("{start_label}:"))?;

        if let Some(cond_expr) = cond {
            self.emit_expr(cond_expr)?;
            self.push_section("text", &format!("
    pop rax
    test rax, rax
    jz {end_label}
"))?;
        }
        //body
        self.loop_stack.push((step_label.clone(), end_label.clone()));
        self.emit_stmt(body, ret_label)?;
        self.loop_stack.pop();

        //step
        self.push_section("text", &format!("{step_label}:"))?;
        if let Some(step_expr) = step {
            self.emit_expr(step_expr)?;
            self.push_section("text", "    pop rax")?;
        }

        self.push_section("text", &format!("    jmp {start_label}"))?;
        self.push_section("text", &format!("{end_label}:"))?;

        self.func.local_scopes.pop();
        Ok(())
    }
    
    fn emit_expr(&mut self, expr: &Expr) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_expr";

        let ty = match expr {
            Expr::BoolLiteral(val) => {
                self.push_section("text", &format!("    push qword {} ; bool literal",
                    if *val {1} else {0} 
                ))?;
                TypeName::Builtin(BuiltinType::Bool)
            }
            Expr::IntLiteral(val) => {
                self.push_section("text", &format!("    push qword {val} ; int literal"))?;
                TypeName::Builtin(BuiltinType::Int64)
            }
            Expr::FloatLiteral(val) => {
                return self.error(ERROR_STRING_ROOT, "Floats are not supported!");
                TypeName::Builtin(BuiltinType::Float64)
            }
            Expr::CharLiteral(val) => {
                self.push_section("text", &format!("    push qword '{}' ; char literal",
                    val
                ))?;
                TypeName::Builtin(BuiltinType::Char)
            }
            Expr::StringLiteral(val) => {
                let str_ptr = self.emit_static_initializer_value(expr)?;
                self.push_section("text", &format!("    push {str_ptr}"))?;
                TypeName::Builtin(BuiltinType::String)
            }
            Expr::Identifier(id) => {
                self.emit_identifier(id)?
            }
            Expr::Grouping(expr) => {
                self.emit_expr(expr)?
            }
            Expr::Prefix{op, expr} => {
                self.emit_prefix(op, expr)?
            }
            Expr::Postfix{op, expr} => {
                self.emit_postfix(op, expr)?
            }
            Expr::Binary{left, op, right} => {
                self.emit_binary(left, op, right)?
            }
            Expr::Assign {left, op, right} => {
                self.emit_assign(left, op, right)?
            }
            Expr::Cast {Type, expr} => {
                self.emit_cast(Type, expr)?
            }
            Expr::Call { .. } => {
                return self.error(ERROR_STRING_ROOT, "Function calls are not implemented in backend yet");
            }
            Expr::Index { .. } => {
                return self.error(ERROR_STRING_ROOT, "Index expressions are not implemented in backend yet");
            }
            Expr::Member { .. } => {
                return self.error(ERROR_STRING_ROOT, "Member access is not implemented in backend yet");
            }
        };
        Ok(ty)
    }
    fn emit_identifier(&mut self, id: &str) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_identifier";
        let mut text = String::new();
                
        let ret = if let Ok(te) = self.lookup_local_var(id) {
            let (offset, t) = te;
            let typesize = self.type_size(&t)?;
            if typesize != 8 {
                match self.type_sign(&t)? {
                    Sign::Unsigned => {
                        text.push_str(&format!("    movzx rax, {} [rbp{}] ; {}\n",
                            self.size_specifier(typesize)?,
                            self.format_offset(offset),
                            id
                        ));
                    }
                    Sign::Signed => {
                        text.push_str(&format!("    movsx rax, {} [rbp{}] ; {}\n",
                            self.size_specifier(typesize)?,
                            self.format_offset(offset),
                            id
                        ));
                    }
                };
                text.push_str(&format!("    push rax ; {}\n",
                    id
                ));
            }
            else {
                text.push_str(&format!("    push qword [rbp{}] ; {}\n",
                    self.format_offset(offset),
                    id
                ));
            }
            t
        }
        else {
            let t: TypeName = self.lookup_global_var(id)?;
            let typesize = self.type_size(&t)?;
            if typesize != 8 {
                match self.type_sign(&t)? {
                    Sign::Unsigned => {
                        text.push_str(&format!("    movzx rax, {} [{}] ; {id}\n",
                            self.size_specifier(typesize)?,
                            id
                        ));
                    }
                    Sign::Signed => {
                        text.push_str(&format!("    movsx rax, {} [{}] ; {id}\n",
                            self.size_specifier(typesize)?,
                            id
                        ));
                    }
                };
                text.push_str(&format!("    push rax ; {}\n",
                    id
                ));
            }
            else {
                text.push_str(&format!("    push qword [{}] ; {id}\n",
                    id
                ));
            }
            t
        };

        self.push_section("text", &text)?;

        Ok(ret)
    }
    fn emit_prefix(&mut self, op: &PrefixOp, expr: &Box<Expr>) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_prefix";

        let ret = match op {
            PrefixOp::LogicalNot => {
                self.emit_expr(expr)?;

                self.push_section("text", "    pop rax")?;
                self.push_section("text", "    test rax, rax")?;
                self.push_section("text", "    setz al")?;
                self.push_section("text", "    movzx rax, al")?;
                self.push_section("text", "    push rax")?;

                TypeName::Builtin(BuiltinType::Bool)
            }
            PrefixOp::BitwiseNot => {
                let expr_type = self.emit_expr(expr)?;
                self.push_section("text", "    pop rax")?;
                self.push_section("text", "    not rax")?;
                self.push_section("text", "    push rax")?;

                expr_type
            }
            PrefixOp::Inc => {
                let expr_type = self.emit_expr(expr)?;
                self.push_section("text", "    pop rax")?;
                self.push_section("text", "    inc rax")?;
                self.push_section("text", "    push rax")?;
                expr_type
            }
            PrefixOp::Dec => {
                let expr_type = self.emit_expr(expr)?;
                self.push_section("text", "    pop rax")?;
                self.push_section("text", "    dec rax")?;
                self.push_section("text", "    push rax")?;
                expr_type
            }
            PrefixOp::Plus => {
                let expr_type = self.emit_expr(expr)?;
                self.push_section("text", "    nop ;unary +")?;
                expr_type
            }
            PrefixOp::Neg => {
                let expr_type = self.emit_expr(expr)?;
                self.push_section("text", "    pop rax")?;
                self.push_section("text", "    neg rax")?;
                self.push_section("text", "    push rax")?;

                expr_type
            }
            PrefixOp::Ref => {
                let ty = self.emit_addr(expr)?;
                TypeName::Pointer(Box::new(ty))
            }
            PrefixOp::Deref => {
                let ptr_ty = self.emit_expr(expr)?;

                let inner_ty = match ptr_ty {
                    TypeName::Pointer(inner) => *inner,
                    _ => return self.error(ERROR_STRING_ROOT, "Cannot dereference non-pointer"),
                };

                let size = self.type_size(&inner_ty)?;

                self.push_section("text", "    pop rax")?;

                match size {
                    1 => match self.type_sign(&inner_ty)? {
                        Sign::Unsigned => self.push_section("text", "    movzx rax, byte [rax]")?,
                        Sign::Signed => self.push_section("text", "    movsx rax, byte [rax]")?,
                    },
                    2 => match self.type_sign(&inner_ty)? {
                        Sign::Unsigned => self.push_section("text", "    movzx rax, word [rax]")?,
                        Sign::Signed => self.push_section("text", "    movsx rax, word [rax]")?,
                    },
                    4 => match self.type_sign(&inner_ty)? {
                        Sign::Unsigned => self.push_section("text", "    mov eax, dword [rax]")?,
                        Sign::Signed => self.push_section("text", "    movsxd rax, dword [rax]")?,
                    },
                    8 => self.push_section("text", "    mov rax, qword [rax]")?,
                    _ => return self.error(ERROR_STRING_ROOT, "Unsupported dereference size"),
                }

                self.push_section("text", "    push rax")?;
                inner_ty
            }
        };
        Ok(ret)
    }
    fn emit_addr(&mut self, expr: &Expr) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_addr";
    
        match expr {
            Expr::Identifier(name) => {
                if let Ok((offset, ty)) = self.lookup_local_var(name) {
                    self.push_section("text", &format!(
                        "    lea rax, [rbp{}] ; &{}",
                        self.format_offset(offset),
                        name
                    ))?;
                    Ok(ty)
                }
                else {
                    let ty = self.lookup_global_var(name)?;
                    self.push_section("text", &format!(
                        "    lea rax, [{}] ; &{}",
                        name,
                        name
                    ))?;
                    Ok(ty)
                }
            }
            Expr::Prefix {
                op: PrefixOp::Deref,
                expr,
            } => {
                let ptr_ty = self.emit_expr(expr)?;
    
                self.push_section("text", "    pop rax ; pointer value used as address")?;
    
                match ptr_ty {
                    TypeName::Pointer(inner) => Ok(*inner),
    
                    other => self.error(
                        ERROR_STRING_ROOT,
                        &format!("Cannot dereference non-pointer type {:?}", other),
                    ),
                }
            }
            Expr::Index { .. } => {
                return self.error(ERROR_STRING_ROOT, "Index expressions are not addressable yet");
            }
            Expr::Member { .. } => {
                return self.error(ERROR_STRING_ROOT, "Member expressions are not addressable yet");
            }
            _ => {
                return self.error(ERROR_STRING_ROOT, "Expression is not addressable");
            }
        }
    }
    fn emit_postfix(&mut self, op: &PostfixOp, expr: &Box<Expr>) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_postfix";
    
        let expr_type = self.emit_addr(expr)?;
        let size = self.type_size(&expr_type)?;
    
        self.push_section("text", "    mov rcx, rax ; postfix address")?;
    
        match size {
            1 => match self.type_sign(&expr_type)? {
                Sign::Unsigned => self.push_section("text", "    movzx rax, byte [rcx]")?,
                Sign::Signed => self.push_section("text", "    movsx rax, byte [rcx]")?,
            },
    
            2 => match self.type_sign(&expr_type)? {
                Sign::Unsigned => self.push_section("text", "    movzx rax, word [rcx]")?,
                Sign::Signed => self.push_section("text", "    movsx rax, word [rcx]")?,
            },
    
            4 => match self.type_sign(&expr_type)? {
                Sign::Unsigned => self.push_section("text", "    mov eax, dword [rcx]")?,
                Sign::Signed => self.push_section("text", "    movsxd rax, dword [rcx]")?,
            },
    
            8 => {
                self.push_section("text", "    mov rax, qword [rcx]")?;
            }
    
            _ => {
                return self.error(ERROR_STRING_ROOT, "Unsupported postfix operand size");
            }
        }
    
        // Postfix result is the old value.
        self.push_section("text", "    push rax ; postfix old value")?;
    
        match op {
            PostfixOp::Inc => {
                self.push_section("text", "    inc rax")?;
            }
    
            PostfixOp::Dec => {
                self.push_section("text", "    dec rax")?;
            }
        }
    
        self.push_section("text", &format!(
            "    mov {} [rcx], {}",
            self.size_specifier(size)?,
            self.format_reg_size("rax", size)?
        ))?;
    
        Ok(expr_type)
    }
    fn emit_binary(&mut self, left: &Box<Expr>, op: &BinaryOp, right: &Box<Expr>) -> Result<TypeName, String> {
        let ERROR_STRING_ROOT = "velc:CodeGenerator:emit_postfix";

        let expr_type = self.emit_expr(left)?;
        let ret = match op {
            BinaryOp::Add => {
                self.push_section("text", "    pop rax")?;
                self.push_section("text", "    inc rax")?;
                self.push_section("text", "    push rax")?;
                expr_type
            }
            BinaryOp::Sub => {
                expr_type
            }
            BinaryOp::Mul => {
                expr_type
            }
            BinaryOp::Div => {
                expr_type
            }
            BinaryOp::Mod => {
                expr_type
            }

            BinaryOp::Eq => {
                expr_type
            }
            BinaryOp::Neq => {
                expr_type
            }
            BinaryOp::Lt => {
                expr_type
            }
            BinaryOp::Gt => {
                expr_type
            }
            BinaryOp::Lte => {
                expr_type
            }
            BinaryOp::Gte => {
                expr_type
            }

            BinaryOp::BitwiseAnd => {
                expr_type
            }
            BinaryOp::BitwiseOr => {
                expr_type
            }
            BinaryOp::BitwiseXor => {
                expr_type
            }
            BinaryOp::Lshift => {
                expr_type
            }
            BinaryOp::Rshift => {
                expr_type
            }

            BinaryOp::LogicalAnd => {
                expr_type
            }
            BinaryOp::LogicalOr => {
                expr_type
            }
            BinaryOp::LogicalXor => {
                expr_type
            }
        };
        Ok(ret)
    }
    fn emit_assign(&mut self, left: &Box<Expr>, op: &AssignOp, right: &Box<Expr>) -> Result<TypeName, String> {
        todo!()
    }
    fn emit_cast(&mut self, t: &TypeName, expr: &Box<Expr>) -> Result<TypeName, String> {
        todo!()
    }





    fn error<T>(&self, base: &str, err: &str) -> Result<T, String> {
        Err(format!("{base}:{err}\n"))
    }

}

